# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Tawazon' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'SwiftVideoBackground'
    pod 'lottie-ios'
    pod 'SwiftMessages'
    pod 'FBSDKLoginKit'
   # pod 'AudioPlayerManager'
    pod 'Firebase/Core', '~> 7.6.0'
    pod 'Firebase/Messaging', '~> 7.6.0'
    pod 'Firebase/DynamicLinks', '~> 7.6.0'
    pod 'Firebase/Crashlytics', '~> 7.6.0'
    pod 'Firebase/RemoteConfig'
    pod 'SwiftyStoreKit'
    pod 'NVActivityIndicatorView'
    pod 'AppsFlyerFramework'
    
    pod 'UXCam'
    target 'TawazonTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'TawazonUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
