# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Tawazon' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod 'GoogleUtilities'
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'SwiftVideoBackground'
    pod 'lottie-ios'
    pod 'SwiftMessages'
    pod 'FBSDKLoginKit'
    # pod 'AudioPlayerManager'
    pod 'Firebase/Core', '~> 7.6.0'
    pod 'Firebase/Messaging', '~> 7.6.0'
    pod 'Firebase/DynamicLinks', '~> 7.6.0'
    pod 'Firebase/Crashlytics', '~> 7.6.0'
    pod 'Firebase/RemoteConfig'
    pod 'SwiftyStoreKit'
    pod 'NVActivityIndicatorView'
    pod 'AppsFlyerFramework'
    #    pod 'Branch', :git => 'https://github.com/BranchMetrics/ios-branch-deep-linking.git'
    pod 'UXCam'
    pod 'LabelSwitch'
#    pod 'Charts'
    pod 'Adapty', '~> 2.4.1'
    
    target 'TawazonTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'TawazonUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'TawazonPNServiceExt' do
        inherit! :search_paths
        pod 'GoogleUtilities'
        pod 'Firebase/Messaging', '~> 7.6.0'
        
    end
    
    
end
